# Generated by Django 3.0 on 2020-02-07 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(default='ww', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be Valid Phone number , should not include country Code & must have 10 digit ', regex='^[6-9]\\d{9}$')]),
        ),
    ]
