# Generated by Django 3.0 on 2020-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='err', max_length=40),
            preserve_default=False,
        ),
    ]
