# Generated by Django 3.0 on 2020-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auditorium',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='auditorium')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('water_f', models.BooleanField()),
                ('toilet_f', models.BooleanField()),
                ('snacks_f', models.BooleanField()),
                ('wifi_f', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('pricePH', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='computerlab',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='auditorium')),
                ('name', models.CharField(max_length=50)),
                ('system_specs', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('water_f', models.BooleanField()),
                ('toilet_f', models.BooleanField()),
                ('snacks_f', models.BooleanField()),
                ('wifi_f', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('pricePH', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='auditorium')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('water_f', models.BooleanField()),
                ('toilet_f', models.BooleanField()),
                ('snacks_f', models.BooleanField()),
                ('wifi_f', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('pricePH', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
