# Generated by Django 3.0 on 2020-02-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookConference',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_from', models.DateTimeField()),
                ('book_till', models.DateTimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookComputerlab',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_from', models.DateTimeField()),
                ('book_till', models.DateTimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.computerlab')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuditorium',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_from', models.DateTimeField()),
                ('book_till', models.DateTimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.auditorium')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
